name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew 

    - name: Set environment variables
      env:
        JASYPTKEY: ${{ secrets.JASYPTKEY }}
        ALLEN_API_ID: ${{ secrets.ALLEN_API_ID }}
        KRX_API_ID: ${{ secrets.KRX_API_ID }}
        NAVER_API_ID: ${{ secrets.NAVER_API_ID }}
        NAVER_API_SECRET: ${{ secrets.NAVER_API_SECRET }}
      run: echo "Environment variables configured."
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build
      env:
        JASYPTKEY: ${{ secrets.JASYPTKEY }}
        ALLEN_API_ID: ${{ secrets.ALLEN_API_ID }}
        KRX_API_ID: ${{ secrets.KRX_API_ID }}
        NAVER_API_ID: ${{ secrets.NAVER_API_ID }}
        NAVER_API_SECRET: ${{ secrets.NAVER_API_SECRET }}

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
